// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

 int config_global_maximum_sell;
 int config_global_drop;
 int config_global_drop_base_rate;
 int config_global_mvp_drop;
 int config_global_mvp_drop_rate;
 int config_main_item_drop_id;
 int config_main_item_drop_delay;
 int config_invulnerable_break_rate;
 int config_invulnerable_break_value;
 int config_infinite_defense_break_rate;
 int config_perfect_dodge_break_rate;
 int config_perfect_dodge_break_value;
 int config_enchantment_clickable;
 int config_enchantment_maximum;
 int config_all_equipment_refinable;
 int config_all_equipment_gradable;
 int config_all_equipment_skip_gender;
 int config_all_equipment_skip_class;
 int config_all_equipment_skip_job;
 int config_all_item_buying_store;
 int config_all_item_no_bind;
 int config_all_item_trade;
 int config_equipment_drop_auto_identify;
 int config_random_monster_rank;
 int config_auto_trade_player_count;
 int config_monster_rank_damage_mode;
 int config_monster_rank_defense_mode;
 int config_monster_rank_exp_bonus_mode;
 int config_monster_rank_drop_bonus_mode;
